# Numpy 
- numerical python
- vectorized programming
- handling multidimensional data
- Manipulating Arrays
- We can define the datatype
- Commonly used with numerical data. But you may use mixed data as well
- Faster execution
- Less Memory
- Most of the mathematical functions are availble
    - linear Algebra
    - statistics
    - probability
    - Fourier transform
    - Trigonometric
    - Logarithemic
    - Exponential

In [1]:
# version 
import numpy
numpy.__version__ # atribute "__"- dunder

'1.16.2'

In [2]:
# importing a package with alias name
import numpy as np

##### converting existing data into numpy array

In [9]:
l = [7,9,0,3,4]
array_1d = np.array(l)
print(type(array_1d))
print(array_1d)

<class 'numpy.ndarray'>
[7 9 0 3 4]


In [6]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [10]:
t = (7,9,0,3,4)
array_1d = np.array(t)
print(type(array_1d))
print(array_1d)

<class 'numpy.ndarray'>
[7 9 0 3 4]


In [22]:
d = {1:1,2:4,3:9}
array_1d =np.array(list(d.values()))
array_1d

array([1, 4, 9])

###### Initializing Arrays

In [23]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
array_zeros = np.zeros((3,3))
print(array_zeros.dtype)
print(type(array_zeros))

float64
<class 'numpy.ndarray'>


In [27]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [29]:
array_zeros = np.zeros((3,3),dtype=int)
print(array_zeros.dtype)
print(type(array_zeros))
print(array_zeros)

int32
<class 'numpy.ndarray'>
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [30]:
array_ones = np.ones((3,3),dtype=int)
print(array_ones.dtype)
print(type(array_ones))
print(array_ones)

int32
<class 'numpy.ndarray'>
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [32]:
array_ones = np.ones((3,2),dtype=bool)
print(array_ones.dtype)
print(type(array_ones))
print(array_ones)

bool
<class 'numpy.ndarray'>
[[ True  True]
 [ True  True]
 [ True  True]]


In [33]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [34]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

###### Creating Arrays with in a specific range

In [41]:
print(np.arange(6))
print(np.arange(1,6))
print(np.arange(1,6,2))
print(np.arange(1,6,0.5))
#print(list(range(1,6,0.5)))

[0 1 2 3 4 5]
[1 2 3 4 5]
[1 3 5]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]


In [44]:
print(np.linspace(1,5,10))
print(np.linspace(1,5,3))
print(np.linspace(1,5,2))

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1. 3. 5.]
[1. 5.]


In [52]:
np.random.randint(10) # output range 0 to 9

8

In [54]:
np.random.randint(10,size=(2,3))

array([[8, 1, 5],
       [9, 0, 3]])

In [55]:
np.random.randint(10,size=(2))

array([0, 3])

In [56]:
np.random.randint(10,34,size=(2))

array([16, 26])

In [59]:
multi_array = np.random.randint(1,1000,size=(10,10))
multi_array

array([[886, 327, 155, 663, 802, 293, 228, 807,  84, 289],
       [751, 640, 566, 106, 461, 115, 600, 669, 201, 494],
       [820, 615, 648, 729, 256, 558, 975, 998, 375, 911],
       [293, 852,  49, 468, 794, 395, 266, 117, 618, 940],
       [639, 626, 169, 336, 168, 275, 132, 948, 892, 264],
       [606, 109, 969, 414, 704, 753, 638,  69, 886, 670],
       [493, 400, 923, 772, 317, 493,  64, 184, 553, 307],
       [353, 373, 204, 368, 412, 947, 219, 303, 655, 393],
       [355, 252, 228, 257, 479, 587,  60, 529, 498, 123],
       [215,  47, 531, 962, 632, 482, 146, 646, 997, 187]])

In [60]:
array_1d,array_ones,array_zeros

(array([1, 4, 9]), array([[ True,  True],
        [ True,  True],
        [ True,  True]]), array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]))

In [65]:
print(array_1d.dtype) # data type of the array
print(array_1d.shape) # shape as a tuple
print(array_1d.ndim) # no of dimensions
print(array_1d.size) # no of items in the array
print(array_1d.itemsize) # size in bytes
print(array_1d.nbytes) # itemsize * no of items

int32
(3,)
1
3
4
12


In [64]:
t= (5,)
print(t,type(t))

(5,) <class 'tuple'>


updating the values in an array

In [66]:
array_1d

array([1, 4, 9])

In [67]:
array_1d[1] = 3
array_1d

array([1, 3, 9])

In [70]:
array_zeros[0] =5
array_zeros

array([[5, 5, 5],
       [0, 0, 0],
       [0, 0, 0]])

In [74]:
# how to update the 2nd row 3rd element
array_zeros[1][2] = 6
array_zeros

array([[5, 5, 5],
       [0, 0, 6],
       [0, 0, 0]])

In [71]:
# check for loop with 1d and 2d arrays
for i in array_1d:
    print(i)
    break

1


In [73]:
for i in array_zeros:
    print(i)
    break

[5 5 5]


Mathematical Opeartors 

In [79]:
a = np.arange(1,11)
b = np.arange(10,20)
print(a+b)
print(a*b)
print(b/a)
print(b//a)
print(b%a)
print(a**2)

[11 13 15 17 19 21 23 25 27 29]
[ 10  22  36  52  70  90 112 136 162 190]
[10.          5.5         4.          3.25        2.8         2.5
  2.28571429  2.125       2.          1.9       ]
[10  5  4  3  2  2  2  2  2  1]
[0 1 0 1 4 3 2 1 0 9]
[  1   4   9  16  25  36  49  64  81 100]


In [81]:
print(a>5)
print(a==5)
print(a<5)

[False False False False False  True  True  True  True  True]
[False False False False  True False False False False False]
[ True  True  True  True False False False False False False]
